# Define TELEGRAM_TOKEN in settings
# Check https://github.com/Huachao/vscode-restclient#system-variables

@myChatId = 1878312143

### Set WebHook
GET https://api.telegram.org/bot{{TELEGRAM_TOKEN}}/setWebhook
    ?url=https://qnvwpmtvyplwcgctxjty.supabase.co/functions/v1/automatic-reply

### Delete webhook
GET https://api.telegram.org/bot{{TELEGRAM_TOKEN}}/deleteWebhook

### Send Message
POST https://api.telegram.org/bot{{TELEGRAM_TOKEN}}/sendMessage
Content-Type: application/json

{
    "chat_id": {{myChatId}},
    "text": "Hello!"
}
